### ISSUE TITLE
Docker images not running on Apple M1

### ISSUE THREAD

**Issue by mark-sivill-kong** [yesinteractive/dadjokes#2]
Hi,

  Would it be possible to also provide docker hub images for multiple os architectures including Apple M1 ( linux/arm64/v8 ) running docker.io/yesinteractive/dadjokes via docker command causes the program to exit straight away on Apple M1.

```
docker run -d \                       
  -p 8100:8100 \
  -p 8143:8143 \
  -e DADJOKES_NOECHO=FALSE \
  docker.io/yesinteractive/dadjokes
```

  Building directly from source things run correctly using `docker-compose up --build` on 

```
version: '3.9'

services:

  # doesn't run on Apple M1
  dadjokesimage:
    image: docker.io/yesinteractive/dadjokes
    environment:
      - DADJOKES_NOECHO=FALSE
    ports:
      - 7100:8100
      - 7143:8143

  # builds and runs OK on Apple M1
  dadjokesbuild:
    build: https://github.com/yesinteractive/dadjokes.git
    environment:
      - DADJOKES_NOECHO=FALSE
    ports:
      - 9100:8100
      - 9143:8143

```

Returns error  `AH00023: Couldn't create the mpm-accept mutex` for dadjokesimage.

As a workaround building directly from git source works (dadjokesbuild) currently with the trade-off of additional build time.

Thanks

Mark
